### PR TITLE
Feature/git workflow

### PR DESCRIPTION
**Pull request by jakenewby**

### CODE REVIEW

**Comment by anthonator** [comment]
I didn't realize this was ready for review

**Comment by jakenewby** [comment]
Hah, yeah.  I heard you talking about it and forgot it was still up here.

**Comment by jakenewby** [comment]
Would you like to have it reverted?

**Comment by anthonator** [comment]
No. We can just open up a new PR for any changes we want to make.

I need to update the contributing guidelines to make the process around this clearer.

**Pull request merged**
