### PR TITLE
Language for code review process

### PR DESCRIPTION
**Pull request by jakenewby**
Language for code review process

### CODE REVIEW

**Comment by jakenewby** [comment]
Looking over thoughtbot's guides, I decided to set this up as a directory instead of a single .md file.  This should provide us the ability to see the contents from inside the directory in Github as well as add any supporting content to the /code-review directory.

**Comment by anthonator** [comment]
Is this from somewhere or is it original?

**Comment by jakenewby** [comment]
I wrote all but this part:
``- That talking face to face may be beneficial to the process.  Face-to-face can often help clarify confusing points.
 - Be humble. ("I'm not sure - let's look it up.")```

**Comment by anthonator** [comment]
Where did it come from?

**Comment by jakenewby** [comment]
Thoughtbot

**Comment by jakenewby** [comment]
merging this, it's been a week!

**Pull request merged**
